name: Aria
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install rclone
        wget https://raw.githubusercontent.com/thereisnothinginhere/heroleechbot0sdaf/master/tobrot/helper_funcs/rclone.conf
    - name: Downloading
      run: |
        pwd
        ls
        mkdir drive
        ls
        rclone mount Shared: drive --vfs-cache-mode writes --daemon --config=rclone.conf
        cd drive
        ls
