name: Test
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        apt install wget
        wget https://raw.githubusercontent.com/HeroTest5/Heroku-Test/main/rclone.sh
        chmod 777 rclone.sh
        bash rclone.sh
